<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectStyle>SDK</ProjectStyle>
    <COM_Supported>false</COM_Supported>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <Import Project="ChaosUtil.Platform.props" />

  <ItemGroup>
    <Compile Include="source/**/*.cs" />

    <None Include="License/*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.6" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
  </ItemGroup>

</Project>